# This is a basic workflow to help you get started with Actions

name: CI-DEV

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Configure current environment
    environment: DEV

    env:
      # SA_TOKEN: ${{ secrets.SA_TOKEN }}
      KUBERNETES_HOSTNAME: ${{ vars.KUBERNETES_HOSTNAME }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Print Secret
        run: echo -n "${{ secrets.SA_TOKEN }}" >> foo && cat foo
      - name: Print Env
        run: echo $KUBERNETES_HOSTNAME
